<br>
<h3>Preparation</h3>
<a target="_blank" href="<?= PageIndex()?>Actions/EventGroups/<?= $event['Event_ID'] ?>">Distribution of competitors by groups</a><br> 
<br>
<h3>Print out</h3>
<a target="_blank" href="<?= PageIndex()?>Actions/EventPrintCompetitors/?ID=<?= $event['Event_ID'] ?>">Print the list of competitors</a><br>
<a target="_blank" href="<?= PageIndex()?>Actions/EventPrintScoreCards/?ID=<?= $event['Event_ID'] ?>">Print competitors cards</a> <br>  
    
<br>
<h3>Scrambles</h3>
    
    <?php 
    $delegate= GetDelegateData();
    if(!$delegate['Delegate_Candidate']){ ?>
        <?php if(file_exists('Scramble/'.$event['Discipline_Code'].'.php')){ ?>
            <?php if(file_exists('Functions/Generate'.$event['Discipline_Code'].'.php')){ ?>
                <a target="_blank" href="<?= PageIndex() ?>Actions/EventGenerateScramble/<?= $event['Event_ID'] ?>">Generate scrambles</a> <nobr>&#9642; scrambles are generated on this site</nobr><br> 
            <?php }else{ ?>
                <?php if(!$event['Discipline_GlueScrambles']){ ?>
                    <a target="_blank" href="<?= PageIndex()?>Actions/EventSetScramblePage/?ID=<?= $event['Event_ID'] ?>">Set scrambles</a> <nobr>&#9642; scrambles generated by TNoodle-WCA or on another site (txt)</nobr><br>
                <?php } ?>
            <?php } ?>
        <?php } ?>    
            <?php if($event['Discipline_GlueScrambles'] and $event['Discipline_TNoodles']){ ?>
                <a target="_blank" href="<?= PageIndex()?>Actions/EventSetGlueScramblesTNoodles/?ID=<?= $event['Event_ID'] ?>">Glue the scrambles</a> <nobr>&#9642; scrambles generated by TNoodle-WCA (pdf)</nobr><br>
            <?php } ?>
            <?php if($event['Discipline_GlueScrambles'] and $event['Discipline_TNoodle']){ ?>
                <a target="_blank" href="<?= PageIndex()?>Actions/EventSetGlueScramblesTNoodle/?ID=<?= $event['Event_ID'] ?>">Glue the scrambles</a> <nobr>&#9642; scrambles generated by TNoodle-WCA (pdf)</nobr><br>
            <?php } ?>
    <?php } ?>           
    <?php 
     $scramble=DataBaseClass::SelectTableRow('Scramble','Event='.$event['Event_ID']);
     if($scramble['Scramble_Timestamp']){ ?>
        <a target="_blank"  href="<?= PageIndex()?>Actions/EventPrintScrambles/?ID=<?= $event['Event_ID'] ?>">Print scrambles</a> <nobr>&#9642; <?= $scramble['Scramble_Timestamp'] ?></nobr><br>
    <?php } ?>            
    <?php $file="Image/Scramble/Hard_".md5($event['Event_ID'].GetIni('PASSWORD','admin')).".pdf";
        if (file_exists($file)){ ?>
            <a target="_blank"  href="<?= PageIndex().$file ?>">Print scrambles</font></a><br>
    <?php }?>
<br>
<h3>Results</h3>
   <a href="<?= PageIndex()?>Actions/EventGenerateScoreTaker/<?= $event['Event_ID'] ?>">Update the link to enter results</a> <nobr>&#9642; If you do not enter the results yourself</nobr>
   <span class="message"><?= GetMessage("EventGenerateScoreTakerMessage") ?></span><br>   
   <a target="_blank" href="<?= PageIndex()?>Actions/ScoreTaker/<?= $event['Event_Secret'] ?>">To enter results</a> <nobr>&#9642; <?= $event['Event_Secret'] ?></nobr><br>     
   <a target="_blank" href="<?= PageIndex()?>Actions/EventPrintResult/?ID=<?= $event['Event_ID'] ?>">Print the results</a><br>    
   <?php if($event['Format_Result']=='Sum'){ ?><a target="_blank" href="<?= PageIndex()?>Actions/EventPrintBestAttempt/?ID=<?= $event['Event_ID'] ?>">Print best attempts</a><br><?php } ?>    

   
<div class="form">
     <b>Comment for Event</b>
     <form method="POST" action="<?= PageIndex()."Actions/EventAddComment" ?>">
         <input name="ID" type="hidden" value="<?= $event['Event_ID'] ?>" />
         <textarea name="Comment" style="height: 100px;width: 400px"><?= $event['Event_Comment']; ?></textarea><br>
         <input type="submit" name="submit" value="Add Comment">
     </form> 
</div>
<br>
<a name="CompetitorEventAdd"></a>
<div class="form">
    <form method="POST" action="<?= PageIndex()?>Actions/CompetitorEventAdd">
        <input name="ID" type="hidden" value="<?= $event['Event_ID'] ?>" />
        <select style="width: 600px" Name="Competitors[]" data-placeholder="Choose <?= html_spellcount($event['Discipline_Competitors'], 'competitor', 'competitors', 'competitors')?>" class="chosen-select chosen-select-<?= $event['Discipline_Competitors'] ?>" multiple>
            <option value=""></option>
            <?php 
                $CompetitorsEventAdd=GetMessage("CompetitorsEventAdd");
                if(!$CompetitorsEventAdd)$CompetitorsEventAdd=array();
                DataBaseClass::FromTable("Competitor","WID is not null or WCAID is not null");
                  DataBaseClass::OrderClear("Competitor", "Name");
            foreach(DataBaseClass::QueryGenerate() as $competitor){ ?>
                <option <?= in_array($competitor['Competitor_ID'],$CompetitorsEventAdd)?'selected':'' ?> value="<?= $competitor['Competitor_ID'] ?>"><?= $competitor['Competitor_WCAID'] ?> <?= $competitor['Competitor_Name'] ?></option>    
            <?php } ?>
        </select>
        <input class="form_enter" type="submit" value="Register">
        <p>
            <span class="message"><?= GetMessage("CompetitorEventAddMessage") ?></font>
            <span class="error"><?= GetMessage("CompetitorEventAddError") ?></font> 
        </p>
    </form>
</div>
<div class="form">
    <form method="POST" action="<?= PageIndex()?>Actions/CompetitorAdd">
       <input type="hidden" name="Event" value="<?= $event['Event_ID'] ?>" />
       <input required name="WCAID" placeholder="WCA ID" value="" /> 
       <input class="form_enter" type="submit" value="Add Person">
       <p>
            <span class="message"><?= GetMessage("CompetitorAddMessage") ?></font>
            <span class="error"><?= GetMessage("CompetitorAddError") ?></font> 
        </p>
    </form>
</div>
<?php
DataBaseClass::Query("select Com.*, count(A.ID) Attempt  "
        . " from Command Com"
        . " left outer join Attempt A on A.Command=Com.ID"
        . " where Com.Event=".$event['Event_ID'].""
        . " group by Com.ID"
        );
$commands=DataBaseClass::getRows();
$deleter=true;
$deleter_names=array();
foreach($commands as $row){
    if(!$row['Attempt'] and !$row['Decline'] ){
        $deleter=false;  
    }else{
       if($row['Decline']){ 
            $deleter_names[]=$row['vName'];
       }
    }
}
if($deleter and sizeof($deleter_names)>0){?>
<br>
<div class="form">
    <form method="POST" action="<?= PageIndex()?>Actions/EventDeleteDeclinedCompetitors" onsubmit="return confirm('Attention: Confirm Delete <?= sizeof($deleter_names)?> declined <?= $event['Discipline_Competitors']>1?'teams':'competitors' ?> !')">
       <?= implode("<br>",$deleter_names) ?><br>
       <input name="ID" type="hidden" value="<?= $event['Event_ID'] ?>" />
       <input class="delete" type="submit" value="Delete declined <?= $event['Discipline_Competitors']>1?'teams':'competitors' ?>">
    </form>
</div>
<?php } ?>
<h3>Competitors</h3> 
<table class="competitions">
    <tr class="tr_title">
        <td>ID</td>
        <td>Group</td>
        <td>Status</td>
        <td><?= $event['Discipline_Competitors']>1?'Teams':'Competitors' ?></td>
        <td/>
        <td>Video</td>
    </tr>
    <tbody> 
<?php
    $n=1;
    
    ?>    
    <?php foreach($commands as $command){ ?>   
     <tr>  
         <td>
                 <?= $command['CardID']; ?>
         </td>
         <td>
                <?= Group_Name($command['Group']) ?>
         </td>
         <td>
             <?php if($command['Decline']){ ?>
                <span class="error">Decline</span>
             <?php } ?>
            <?php if($command['Attempt']){ ?>
                <span class="message">Result</span>
             <?php } ?>
         </td>
         <td>  
            <?php 
            $WCAIDs=array();
            $Countries=array();

            DataBaseClass::FromTable('CommandCompetitor',"Command=".$command['ID']);
            DataBaseClass::Join_current('Competitor');
            DataBaseClass::OrderClear('Competitor', 'Name');
            $names=array();
            $competitors=DataBaseClass::QueryGenerate();
            for($i=0;$i<$event['Discipline_Competitors'];$i++){ ?> 
                <div class="competitor_td">
                    <nobr>
                        <?php if(isset($competitors[$i])){
                                $competitor=$competitors[$i];
                                $names[]=$competitor['Competitor_Name']; ?>
                                <?= $competitor['Competitor_Name'] ?> &#9642; <?= $competitor['Competitor_WCAID']; ?> &#9642; <?= $competitor['Competitor_Country']; ?>
                                <?php if(!$competitor['CommandCompetitor_CheckStatus']){ ?>
                                    &#9642; <span class="error">no on WCA</span>
                                <?php } ?>
                        <?php }else{ ?>
                            &#9642;
                        <?php } ?>    
                    </nobr>
                </div>
            <?php } ?>
        </td>
       
        <td>
            <?php if(!$command['Attempt']){ ?>
            <form name="CompetitorRowChange" id="CompetitorRowDelete_<?= $command['ID']?>" method="POST" 
                  action="<?= PageIndex()."Actions/CompetitorEventDelete" ?> " 
                  onsubmit="return confirm('Attention: Confirm deletion!\nDelete <?= implode(", ",$names)?>?')">
                <input name="ID" type="hidden" value="<?= $command['ID'] ?>" />
                <input class="form_row delete" type="submit" value="X">
            </form>
            <?php }else{ ?>
                <span id="CompetitorRowDelete_<?= $command['ID']?>"/>
            <?php } ?>
        </td>
        <td>
            <form  method="POST" action="<?= PageIndex()."Actions/CompetitorEventVideo" ?> " >
                <input name="ID" type="hidden" value="<?= $command['ID'] ?>" />
                <input  name="Video" value="<?= $command['Video'] ?>">
                <input class="form_row" type="submit" value="Save" style="margin:0px; padding:1px 2px;">
            </form>
        </td>
        </tr>
    <?php } ?>
        </tbody>
 </table>
</div>
